name: lefthook_dart
description: wrapper of lefthook (Git hooks manager) for flutter and dart
version: 1.0.5
homepage: https://github.com/idNoRD/lefthook_dart
environment:
  sdk: '>=3.8.0 <4.0.0'
executables:
  lefthook: lefthook_dart
dependencies:
  archive: ^4.0.7
  system_info2: ^4.0.0
  cli_util: ^0.4.2
dev_dependencies:
  lints: ^6.0.0
